version: "3.8"

services:
  app:
    image: trisaptono123/ticket-booking-app:2024.1.7
    container_name: ticket-booking
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database
    entrypoint: ["go", "run", "main.go"]
    networks:
      - ticket_network

  database:
    image: postgres:15
    container_name: ticket_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket_network

volumes:
  postgres_data:

networks:
  ticket_network:
    driver: bridge
