on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 22
          script: |
            echo "Pulling the latest Docker image..."
            cd /home/junxgurit/app/ticket-booking
            docker pull ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7
            docker-compose down
            docker-compose up -d
