name: Deploy to VPS

on:
  push:
    branches:
      - main # Menjalankan saat ada push ke branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH to Server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd app/ticket-booking
            git pull origin main
            # Perintah lain untuk deploy, misalnya:
            docker-compose down
            docker-compose up -d
          EOF
