name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7

      - name: Set up SSH key
        uses: webfactory/ssh-agent-action@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker container on Ubuntu Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.UBUNTU_SERVER_IP }} <<EOF
            # Navigate to the application directory
            cd /home/ubuntu/my-app
            
            # Optionally, pull latest code (if necessary)
            git pull origin main

            # Stop any running container using the same image (if needed)
            docker-compose down

            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7

            # Start the container with Docker Compose (or using docker run)
            docker-compose up -d  # Or: docker run -d ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7

            # If using Docker Compose, you can also restart services like so:
            # docker-compose restart
          EOF
