jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build Docker image
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7
          docker images  # Debugging step to list the images

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7

      # SSH to VPS and Deploy Docker Image
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            echo "Pulling the latest Docker image from Docker Hub"
            docker pull ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7
            echo "Stopping the old container"
            docker stop ticket-booking || true
            echo "Removing the old container"
            docker rm ticket-booking || true
            echo "Starting the new container"
            docker run -d --name ticket-booking -p 8081:8080 ${{ secrets.DOCKER_USERNAME }}/ticket-booking-app:2024.1.7
