name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # SSH to VPS and deploy
      - name: Pull latest changes and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            # Navigate to the app folder
            cd /app/ticket-booking
            # Pull the latest changes from GitHub
            git pull origin main
            # Build and restart the Docker container
            docker-compose down
            docker-compose up --build -d
